name: Reusable workflow for compilation, tests, installation and examples, from sources

on:
  workflow_call:
    inputs:
      image-version:
        required: true
        type: string

jobs:
  from-sources:
    runs-on: ubuntu-latest
    container: smtcoq/smtcoq:latest-${{ inputs.image-version }}
    strategy:
      fail-fast: false  # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v3
      - run: |
          sudo chown -R coq:coq .
          cd src
          make
          make test
          make install
          make clean
          cd ../examples
          coqc Example.v
          cd ..
          sudo chown -R 1001:116 .
