name: Reusable workflow for installation and examples, from opam

on:
  workflow_call:
    inputs:
      image-version:
        required: true
        type: string

jobs:
  from-opam:
    runs-on: ubuntu-latest
    container: smtcoq/smtcoq:latest-${{ inputs.image-version }}
    strategy:
      fail-fast: false  # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: 'coq-smtcoq.opam'
          after_script: |
            startGroup "Check examples"
              sudo chown -R coq:coq .
              cd examples
              coqc Example.v
              cd ..
              sudo chown -R 1001:116 .
            endGroup
